orangehrm/oxd

components/src/core/components/Button/_variables.scss
components/src/core/components/Button/button.scss
components/src/core/components/Dialog/_variables.scss
components/src/core/components/Dialog/close-button.scss
components/src/core/components/Text/_variables.scss
components/src/core/components/Text/text.scss
components/src/styles/_colors.scss
storybook/stories/core/components/Dialog/DialogDeleteConfirmation.story.vue

1. Confirmation Modal's font weight is changed to 600 (as per the oxd guide)
2. Modal close button's background color is changed to #B8BDC7 (to be consistent with the other places in the prodcut)
3. Hover background color in the danger button is corrected
4. space between the icon and the button text is increased to 0.5rem in icon buttons

Change Styles in the components used in the Delete Confirmation Modal

---

components/src/core/components/Button/Icon.vue
components/src/core/components/Button/__tests__/icon-button.spec.ts
components/src/core/components/TableSidebar/__tests__/__snapshots__/TableSidebar.spec.ts.snap

This PR Contains
1. Hide tooltip when button is disabled
2. New property to override the above behavior (showTooltipWhenDisabled)
This is based on Mike's feedback that disabled buttons should not have a tooltip, but that there can be exceptions where it is needed.

ENT - RMP-339 Hide icon button tooltip when button is disabled

---

components/src/core/components/Input/checkbox-input.scss

Checkbox should not have a border when checked according to [OXD Guidelines](https://oxd-prod-infinity.orangehrm.com/pages/check-box.html).

ENT - Remove border from checked checkbox to match OXD guidelines.

---

components/src/core/components/Input/_variables.scss
components/src/core/components/Input/checkbox-input.scss

1. Change checkbox border radius to match that in other OXD screens
2. Keep checkbox size same when checked and unchecked. Earlier checkbox was shrinking because there was no border when checked.

ENT- RMP-200 - fix checkbox border radius, and checkbox size

---

components/src/core/components/CardTable/Table/TableHeaderSortDropdown.vue
components/src/core/components/CardTable/Table/table-header-sort-dropdown.scss

1. Reduced size of table header sort icons to 14px.
2. Changed sort dropdown list icons to match header icons (svg)

ENT - Reduced size of table header sort icons to 14px.

---

components/src/core/components/List/list.scss
components/src/core/components/TableFilter/table-filter.scss
components/src/core/components/TableSidebar/table-left-panel.scss

- Set list container padding to 0.5 rem
- Aligned the other styles to match with the above fix

ENT - RMP-358 "The separator between the left panel and the candidate list is ended in the middle of the list"

---

components/src/core/components/Divider/_variables.scss
components/src/core/components/TableSidebar/table-left-panel.scss
components/src/styles/_colors.scss

- Left panel filter tabs on hover background color changed to #f1f2f5
- Left panel filter tabs font-weight of active status changed to 700
- Color of the divider changed to #eeeff3
- Toggle button icon styles changed
-

ENT - RR2-115  [OXD]UI issues in left menu panel of reports and analytics screen

---

components/src/core/components/List/List.vue
components/src/core/components/List/list.scss
components/src/core/components/ProfilePic/ProfilePic.vue
components/src/core/components/ProfilePic/types.ts

1. Moved "quick-search:onClear" from "quickSearchSelect" method's null condition checker to a separate method called "quickSearchOnClear"
2. added a new size for profile pic component 'extra-small' and fixed quick search issues mentioned by Mike.

ENT - RMP-349 "The loading spinner is shown when it's not required to display"

---

components/src/core/components/List/List.vue
components/src/core/components/List/list.scss

- Reduce width of side panel to 200px
- Set table to flex grow 
- Prevent sidebar shrinking. 
- Remove extra padding on table right

ENT - List component UI changes to increase space available to table

---

components/src/core/components/List/list.scss

1. Allow list container to grow vertically with list. 
2. Align page navigation buttons to right

ENT - list styling changes

---

components/src/core/components/List/List.vue
components/src/styles/_utility.scss

- Set min-height instead of height, to allow container to grow when page size is large.

ENT: Fix list container min-height

---

components/src/core/components/List/list.scss

ENT - fit width of select inside list to it's content

---

components/src/core/components/Button/Button.vue
storybook/stories/core/components/Button/Button.stories.js

Add support to add tooltips for oxd-button when the button is in disabled state only

[RMP-392] Add disabled tooltip for buttons

---

components/src/core/components/List/List.vue

Show brackets around the number of records found. Eg:
(100) Candidates Found
This matches the behavior in goal list.

ENT: Show brackets around number of records found in list

---

components/src/core/components/Input/Autocomplete/AutocompleteInput.vue
components/src/core/components/Input/Autocomplete/QuickSearchInput.vue
components/src/core/components/List/List.vue

1. Added keypress enter event to quick search
2. Triggered dropdown hide when on keypress enter event by accessing child element "dropdownOpen" value through refs.

ENT - RMP-348 Quick search trigger on keypress enter

---

components/src/core/components/CardTable/Cell/link-with-pill.scss

ENT - Align the text of the pill with link text

---

components/src/core/components/List/List.vue

In this PR I've cleared the values of quick search autocomplete by accessing child component's values through refs
Vue App fix
https://websvn.orangehrm.com/orangehrm?op=comp&compare[]=/enterprise/branch/recruitment-vue-conversion/@170618&compare[]=/enterprise/branch/recruitment-vue-conversion/@170619
https://websvn.orangehrm.com/orangehrm?op=comp&compare[]=/enterprise/branch/recruitment-vue-conversion/@170618&compare[]=/enterprise/branch/recruitment-vue-conversion/@170620

ENT - RMP-343 "Search candidate via search box & Perform filter > Searched character isn't getting removed from the search box "

---

components/src/core/components/Input/_variables.scss
components/src/core/components/Input/date-input.scss
components/src/core/components/InputField/input-group.scss

Below points have been addressed in this PR,
- Date pickers in the Filter popup window are not showing based on OXD Guideline
- Spaces and alignment between 2 switch buttons should be 0.5 rem

ENT - RMP-184 "Mentioned UI Issues are there in the Filter modal"

---

components/src/core/components/Calendar/CalendarController.vue
components/src/core/components/Input/DateInput.vue
components/src/directives/focus-first-element/index.ts
components/src/directives/focus-trap/index.ts

Had to create a new function in the Dateinput component to fire when click outside action is happening.
This was setting the focus back to the calendar icon previously.
Clicking outside should remove focus from the component and the calendar icon

ENT - Changes to Focus trap and Focus First element Directives and calendar click outside behaviour 

---

changelog.md
components/src/core/components/Input/Autocomplete/AutocompleteInput.vue

**Scenario**
1. Search for a non existing keyword
2. Again search for matching keyword
**Current behaviour**
Gets "No results found" when the search is running
**Expected behaviour**
Should get "Searching" whenever it's searching
**Given solution**
It happens due to setting the value of "loading" to false in promise "finally". Moved this..loading = false only resolving block.
**_After the fix it only shows "No results found" when the searching is done there's no matching to be shown_**

ENT - RMP-557 - Shows "No results found" instead "Searching "when searching right after getting no results from the previous search 

---

components/src/core/components/Toast/_variables.scss
components/src/core/components/Toast/toast.scss

toasts message contents were center aligned and padding was added as 1 rem as per the discussion with mike

ENT - RR2-270 - OXD Toast message style update 

---

components/src/composables/useSanitize.ts
components/src/core/components/Input/Autocomplete/AutocompleteInput.vue

This is the fix for RMP-660/RMP-661
With this fix I have checked the places where we have used v-html . In lib size there are 2 places
1 - Icon.Vue - It is ok to use
2 - List.vue - It is the quick search overriding slot. That is also fine since the options are sanitized inside autocomplete
There are some usages inside the Buzz module. I assume they are already thought-out since HTML content is handled there.

ENT - adding sanitising  for the highlighted options

---

components/src/core/components/List/List.vue
components/src/core/components/List/list.scss

This fixes both [RMP-545](https://orangehrmenterprise.atlassian.net/browse/RMP-545) and [RMP-548](https://orangehrmenterprise.atlassian.net/browse/RMP-548)
In the comment section it says to add 75vh as its minimum height but it blocks the visibility of the pagination when there're no much records and have to scroll bottom to see the pagination therefore I've added a css calc function as calc(75vh - 100px) to reduce 100px from 75vh

RMP-545 / 548 - bug fixes

---

components/src/core/components/Input/Autocomplete/AutocompleteInput.vue

It is enough to have the id, label after selecting autocomplete and multiselect for it's functionality thus removing unnecessary details

ENT - RMP - 435 : removing unnecessary  details in selected Option after selecting

---

components/src/composables/types.ts
components/src/composables/useField.ts
components/src/composables/useFormValidation.ts
components/src/core/components/Form/Form.vue
components/src/core/components/Input/__tests__/input.spec.ts
components/src/core/components/InputField/InputField.vue
components/src/core/components/InputField/InputGroup.vue
components/src/core/components/Label/Label.vue
components/src/core/components/SchemaForm/SchemaForm.vue
components/src/core/components/SchemaForm/types.ts
storybook/stories/core/components/Input/Input.stories.js
storybook/stories/core/components/Input/InputEvents.story.vue
storybook/stories/core/components/SchemaForm/SchemaForm.stories.js

Following missing items for the Text Input widget has been identified. Refer the [analysis](https://docs.google.com/spreadsheets/d/1Wm9TQmfOHVKBeIpZuRNtsmcmq-wYqr-dF8yuaCzUY6I/edit?usp=sharing) and the [standards](https://docs.google.com/document/d/16_Nd3VxE_lTD9pVkONQ0egn7IiwyX1pVXZjzl-V4tU8/edit#heading=h.5x0d5h95i329).
- HTML Attributes
- Style
- Auto generated ID
- Schema form behaviors
- Cannot trigger validation upon another field change - Ex: Updating Field A should trigger a validation of Field B
- UI Guidelines
- Label associate assistive - Adding the 'for' attribute in the label
- Complete the unit tests
- Story book documentation is not done
- A description
- Props
- Events
- Stories for different behaviors
- Code samples

Ent - Standardise Text Input widget

---

components/src/core/components/Toast/Icon.vue
components/src/core/components/Toast/__tests__/__snapshots__/icon.spec.ts.snap
components/src/core/components/Toast/__tests__/__snapshots__/toast.spec.ts.snap
components/src/core/components/Toast/_variables.scss

In this PR I've increased the toast icon size by considering the goal list icon size.
1. In the goal list the icon size is 30px.
2. converted in to rem and the value is 1.875rem
3. applied it to the oxd toast icon
the above fix will apply to the all the toast types and confirmed with Mike

ENT - RMP-479 - Increased the toast indicator icon size

---

components/src/core/components/CardTable/Cell/table-select-input.scss
components/src/core/components/List/List.vue
components/src/styles/_utility.scss

In this PR,
1. Added display table and table cell utility classes to utility.scss
2. changed the list table wrapper display type from flex to table to maintain same height by referring each others according to [this example in w3schools](https://www.w3schools.com/howto/howto_css_equal_height.asp)

ENT - RMP-477 - "When there are no/fewer records in the system, the vertical separator shouldn’t be ended in the middle"

---

components/src/core/components/CardTable/Cell/table-select-input.scss

In this PR I've removed the text truncate only for the table select dropdown component by overriding the styles of select input as per below comment in this defect
https://orangehrmenterprise.atlassian.net/browse/RMP-541?focusedCommentId=15594

ENT - RMP-541 - bug fix

---

components/src/core/components/Calendar/_variables.scss
components/src/core/components/Calendar/calendar.scss
components/src/core/components/CardTable/Table/table-header-sort-dropdown.scss
components/src/core/components/CardTable/Table/table.scss
components/src/core/components/Input/Select/select-input-button.scss
components/src/core/components/Input/Select/select-input.scss
components/src/core/components/Input/_variables.scss
components/src/styles/_variables.scss

This PR fixes,
**Not consistent with other places in the system**
3. The thickness of the Table header’s border-bottom is different from other places in the system.
**Dropdown Related - (All vacancies/Stage/Action button options )**
1. Inbetween options in a dropdown, a horizontal line is showing - All vacancies, Stage dropdown & action button options
Of the below reopen scenarios
https://orangehrmenterprise.atlassian.net/browse/RMP-444?focusedCommentId=16562

ENT - RMP-444

---

components/src/core/components/Input/DateInput.vue
components/src/core/components/Input/__tests__/date-input.spec.ts

In this PR I've set focused to false when click outside of the text input on the calendar

ENT - RMP-719

---

components/src/core/components/Input/Select/SelectText.vue
components/src/core/components/Input/Select/select-input.scss
components/src/core/components/Input/__tests__/__snapshots__/multiselect-input.spec.ts.snap
components/src/core/components/Input/__tests__/__snapshots__/select-input.spec.ts.snap

This commit contains the fix for the select style with after option

RMP-720 select input style fix

---

changelog.md
components/src/core/components/Input/_variables.scss
components/src/core/components/Input/switch-input.scss

1. Increased the space between the label and the switch to 15px (suggested by Mark. He confirmed it's ok to add in px here)
2. Use the css gap to make sure there's at least 15px between the label and switch when `useFullWidth=true` mode.

Min gap between label and switch

---

components/src/core/components/SchemaForm/types.ts

Fix the Type error in Validator, It didn't had return type for async functions

---

components/src/core/components/Alert/Alert.vue
components/src/core/components/Alert/__tests__/alert.spec.ts
components/src/core/components/Alert/_variables.scss
components/src/core/components/Alert/alert.scss
storybook/stories/core/components/Alert/Alert.stories.js

Which reduces the height and border-radius, to match styles given by Mike for an alert in inside a modal form without buttons.

Added a "compact" mode to Alert

---

components/src/core/components/Input/_variables.scss
components/src/core/components/Input/radio-input.scss

- Remove the border from checked radio input
- Change the active (unchecked) radio input border color to #cfd3de ($oxd-interface-gray-lighten-1-color)

Remove border from checked radio button

---

components/src/core/components/Dialog/Dialog.vue
components/src/directives/focus-trap/index.ts

This commit contains improvement of  focus-trap for dialogs with schema form

ENG-30 focusTrap directive update to support schema form

---

components/src/core/components/Grid/_variables.scss
components/src/core/components/Grid/grid.scss
components/src/core/components/Input/Autocomplete/AutocompleteInput.vue
components/src/core/components/Input/__tests__/autocomplete-input.spec.ts
storybook/stories/core/components/Grid/Grid.stories.js
storybook/stories/core/components/Grid/Grid.story.vue

This is a cherrypicked merge of pull request [OHRM5X-1500: OXD Grid add 8 column support](https://github.com/orangehrm/oxd/pull/408)
* [OHRM5X-1500: OXD Grid add 8 column support](https://github.com/orangehrm/oxd/pull/408/commits/d9e0fa42131b85679c363f1cec40de783913e7ed)
* [OHRM5X-1402: OXD multiselect autocomplete selected items are removed](https://github.com/orangehrm/oxd/pull/408/commits/8514688f48ec47f0c74adc8dfbb0d4f560b3fc35)
* This fix was already there in ent-dev. Merged small formatting change and additional unit tests

Oxd grid 8 col support

---

components/src/core/components/Input/file-input.scss

This commit contains a style fix for file input when uploading a file with a large no of characters

LMR-179 fix in file input upload button style

---

changelog.md
components/src/styles/_utility.scss

show tool tips in multi line if the content is too lengthy

---

yarn.lock

Following warning was seen for a while when when running yarn:
`Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
`
I ran the command given, and it updated the `caniuse-lite` package.

Updated caniuse-lite as prompted by browserslist.

---

components/src/core/components/Comments/Comments.vue
components/src/core/components/Comments/comments.scss

[https://orangehrmenterprise.atlassian.net/browse/RMP-845](https://orangehrmenterprise.atlassian.net/browse/RMP-845)
1. Comments component shouldn't display grey background when "hideEmptyPlaceholder" is true and no comments.
2. Removed an additional space appearing inside the comments container when there are no comments.
3. fixed a sudden movement happening when clearing all the comments and adding a comment when there are no comments.

ENT - RMP-845 - bug fixes

---

changelog.md
components/src/core/components/Icon/icon.scss

Fixed issue with disabled styling of the icon button.
Button/Icon.vue is setting the class --disabled on oxd-icon
`    <oxd-icon
:style="iconStyles"
:size="size"
:class="{'--disabled': disabled}"
:name="name"
/>`
but Icon/Icon.vue expects class `oxd-icon--disabled` for disabled styling.
Updated it to style for both classes `oxd-icon--disabled`  and `--disabled`
Expected Style: https://oxd-prod-infinity.orangehrm.com/pages/button.html

fix disabled styling

---

changelog.md
components/src/core/components/Input/Time/TimeInput.vue
components/src/core/components/Input/__tests__/__snapshots__/time-input.spec.ts.snap
components/src/core/components/Input/__tests__/time-input.spec.ts
storybook/stories/core/components/Input/Time.stories.js

Earlier changes support allowEmpty prop made the time input change to 24 hour.
see: https://orangehrmenterprise.atlassian.net/browse/LMR-363
Changed TimeInput default behavior to allow clearing input value, removing conditional logic related to allowEmpty.
Changed default hint to HH:MM (was HH-MM).

Changed to allow clearing time value, removed allowEmpty prop.

---

changelog.md
components/src/core/components/Input/DateInput.vue

Issue:
1) Type a date into Date Input
2) Open Date Picker, and select a different date. (date picker will close, and focus move to Date Input.
3) Click outside Date input.
4) Date Input will revert to originally typed value in step 1) and date selected in date picker will be lost.
https://user-images.githubusercontent.com/5012626/186898556-3601075d-982e-4b56-92d9-8b14c9e0395b.mp4
Fix:
When Date picker is closed, set `this.dateInput = null`. This code is there in main branch as well.

Fix blur behavior of DateInput

---

components/src/core/components/Input/Select/navigation-mixin.ts

Fix for scenario 6) in RR2-388.
- Keyboard navigation was allowing user to select disabled options from the list.
- Fix was to skip disabled options

Skip disabled items in keyboard navigation - select, multiselect, autocomplete

---

components/src/core/components/Comments/Comments.vue
storybook/stories/core/components/Comments/Comments.stories.js

defined an option set initial scroll. by default it's true and scroll automatically unless set it to false

LAN-42 - defined an option set initial scroll.

---

components/src/core/components/Comments/comments.scss

Specified CSS selector to apply margin bottom only for the section title of the comment group

ENT - LAN-70 - Specified CSS selector more

---

components/src/core/components/Input/Autocomplete/autocomplete-input.scss

fixed close icon alignment issue in autocomplete for 3 main resolutions

---

components/package.json
components/src/core/components/Buzz/BuzzPostInput.vue
components/src/core/components/Buzz/buzz-post-input.scss
components/src/core/components/Tab/tab-container.scss
package.json

OHRM5X-1913: OXD buzz post input not showing line breaks in firefox fix

---

.github/workflows/linting.yml
.github/workflows/storybook.yml
.github/workflows/unit-tests.yml
changelog.md
components/src/core/components/TinyMce/skins/lightgray/content.module.css

LAN-389 - Removed browser default paragraph styles by overriding

---

changelog.md
components/src/core/components/Comments/Comment.vue
components/src/core/components/Comments/Comments.vue
components/src/core/components/Comments/__tests__/comment.spec.ts
components/src/core/components/Comments/comment.scss
storybook/stories/core/components/Comments/Comments.stories.js

LAN-221 - introduced a prop to stack comment delete confirmation message and the actions

---

components/src/core/components/Input/Number/Number.vue
components/src/core/components/Input/__tests__/number.spec.ts
storybook/stories/core/components/Input/Number.stories.js

LAN-715 - changed 'required' name to 'requiredDefaultValue'

---

components/src/core/components/PopOverButton/PopOverButton.vue
components/src/core/components/PopOverButton/pop-over-button.scss

Pop Over button position issue fixed

---

changelog.md
components/src/core/components/ListTable/ListTable.vue
components/src/core/components/ListTable/__tests__/list-table.spec.ts
storybook/stories/core/components/ListTable/Table.stories.js

LAN-610: Add partial loading prop to ListTable component

---

changelog.md
components/src/core/components/Input/Autocomplete/AutocompleteInput.vue
components/src/core/components/Input/Autocomplete/autocomplete-input.scss

Feature - ccs autocomplete dropdown display all items

---

changelog.md
components/src/core/components/Input/Select/navigation-mixin.ts
components/src/core/components/Input/__tests__/navigation-mixin.spec.ts

LAN 951 : onKeypress changed to skip the disabled options when updating the pointer.

Change navigation-mixin to avoid disabled options

---

changelog.md
components/jest.config.js
components/jest.init.js
components/src/composables/__tests__/useFlashing.spec.ts
components/src/composables/useFlashing.ts
components/src/core/components/ListTable/CellContainer.vue
components/src/core/components/ListTable/ClickableCell.vue
components/src/core/components/ListTable/ListTable.vue
components/src/core/components/ListTable/LocalizedCell.vue
components/src/directives/focus-first-element/index.ts
yarn.lock

TEC-165: Fix OXD list table highlighting issue
