orangehrm/oxd

components/src/core/components/CardTable/CardTable.vue, components/src/core/components/CardTable/Decorator/card.scss, components/src/core/components/CardTable/table-row.scss, components/src/core/components/Pagination/page-item.scss, storybook/stories/core/components/CardTable/CardTable.story.vue
- OHRM5X-31/OHRM5X-32/OHRM5X-70 oxd defect fixes
=> OHRM5X-31: Improve Card component 

components/src/core/components/Button/Icon.vue, components/src/core/components/CardTable/Header/DefaultCardHeader.vue, components/src/core/components/Input/DropdownInput.vue, components/src/core/components/Input/FileInput.vue, components/src/core/components/Input/RadioInput.vue, components/src/core/components/Input/__tests__/__snapshots__/radio-input.spec.ts.snap, components/src/core/components/Input/__tests__/radio-input.spec.ts, components/src/core/components/Input/_variables.scss, components/src/core/components/Input/dropdown-input.scss, components/src/core/components/Input/radio-input.scss, components/src/core/components/InputField/InputField.vue, components/src/core/components/InputField/InputGroup.vue, components/src/core/components/InputField/__tests__/__snapshots__/input-field.spec.ts.snap, components/src/core/components/InputField/types.ts, package.json, storybook/stories/core/components/Form/Form.stories.js, storybook/stories/core/components/Form/InputGroupedForm.story.vue, storybook/stories/core/components/Input/DropdownInput.stories.js, storybook/stories/core/components/Input/FileInput.stories.js, storybook/stories/core/components/Input/RadioInput.stories.js, storybook/stories/core/components/InputField/InputField.stories.js
- OXD-Radio Input added
- Issue with Datatable not selecting in prod mode fixed
- OXD-Dropdown indentation support
- Stories/ Unit test updated
=> OHRM5X-162: OXD-Radio Input added

components/src/core/components/Button/Icon.vue, components/src/core/components/Button/_variables.scss, components/src/core/components/Button/icon.scss, components/src/core/components/Calendar/Date.vue, components/src/core/components/Calendar/_variables.scss, components/src/core/components/Calendar/calendar.scss, components/src/core/components/CardTable/CardTable.vue, components/src/core/components/CardTable/Cell/Actions.vue, components/src/core/components/CardTable/Cell/Checkbox.vue, components/src/core/components/CardTable/Cell/DefaultCellContainer.vue, components/src/core/components/CardTable/Cell/default.scss, components/src/core/components/CardTable/Cell/types.ts, components/src/core/components/CardTable/Header/DefaultCardHeader.vue, components/src/core/components/CardTable/Table/TableHeaderCell.vue, components/src/core/components/CardTable/Table/TableHeaderSortDropdown.vue, components/src/core/components/CardTable/Table/_variables.scss, components/src/core/components/CardTable/Table/table-header-cell.scss, components/src/core/components/CardTable/Table/table-header-sort-dropdown.scss, components/src/core/components/CardTable/types.ts, components/src/core/components/Grid/Grid.vue, components/src/core/components/Icon/_variables.scss, components/src/core/components/Icon/icon.scss, components/src/core/components/Input/DropdownInput.vue, components/src/core/components/Input/dropdown-input.scss, components/src/styles/_variables.scss, storybook/stories/core/components/CardTable/CardTable.story.vue, storybook/stories/core/components/CardTable/CardTableRowOptions.story.vue, storybook/stories/core/components/CardTable/SortableCardTable.story.vue, storybook/stories/core/components/CardTable/Table.stories.js
OHRM5X-82: oxd-cardtable row selectable feature
OHRM5X-217: oxd-cardtable sorting
OHRM5X-334: oxd-calendar style fixes
OHRM5X-199: oxd-dropdown stop reset when disabled
=> OHRM5X-323: P1 Defect Fixes

components/package.json, storybook/.storybook/manager.js, storybook/package.json, yarn.lock
Preview: https://rajithakumara-oxd.netlify.app/
=> OHRM5X-354: Add brand image to storybook

components/src/core/components/Input/Autocomplete/AutocompleteInput.vue, components/src/core/components/Input/Autocomplete/autocomplete-input.scss, components/src/core/components/Input/MultiSelect/MultiSelectInput.vue, components/src/core/components/Input/Select/SelectInput.vue, components/src/core/components/Input/Select/select-input.scss, components/src/core/components/Input/__tests__/autocomplete-input.spec.ts, components/src/core/components/Input/_variables.scss, storybook/stories/core/components/Input/SelectInput.stories.js
OHRM5X-427:  oxd-select label wrap fix
OHRM5X-428:  oxd-autocomplete close icon color fix
=> OHRM5X-427:  oxd-select label wrap fix

components/src/core/components/Input/Time/TimeInput.vue, components/src/core/components/Input/Time/TimePicker.vue, components/src/core/components/Input/Time/time-input.scss, components/src/core/components/Input/__tests__/__snapshots__/time-input.spec.ts.snap, components/src/core/components/Input/__tests__/time-input.spec.ts, components/src/core/components/Input/_variables.scss, components/src/core/components/InputField/InputField.vue, components/src/core/components/InputField/types.ts, components/src/directives/click-outside/index.ts, storybook/stories/core/components/Input/Time.stories.js, storybook/stories/core/components/InputField/InputField.stories.js
=> OHRM5X-434: OXD-Time input field added

components/src/core/components/Calendar/Calendar.vue, components/src/core/components/Calendar/CalendarController.vue, components/src/core/components/Calendar/Date.vue, components/src/core/components/Calendar/__tests__/__snapshots__/calendar-controller.spec.ts.snap, components/src/core/components/Calendar/__tests__/__snapshots__/calendar.spec.ts.snap, components/src/core/components/Calendar/__tests__/calendar-controller.spec.ts, components/src/core/components/Calendar/__tests__/calendar.spec.ts, components/src/core/components/Calendar/_variables.scss, components/src/core/components/Calendar/calendar.scss, components/src/core/components/Calendar/types.ts, components/src/core/components/Input/DateInput.vue, components/src/core/components/Input/__tests__/__snapshots__/date-input.spec.ts.snap, components/src/core/components/Input/__tests__/date-input.spec.ts, components/src/core/components/Input/__tests__/time-input.spec.ts, components/src/core/components/Input/_variables.scss, components/src/core/components/Input/date-input.scss, components/src/utils/date.ts, storybook/stories/core/components/Calendar/Calendar.stories.js
=> OHRM5X-432: oxd-calendar attributes & events props added

components/package.json, components/src/composables/types.ts, components/src/composables/useField.ts, components/src/composables/useFormValidation.ts, components/src/core/components/CardTable/Cell/Actions.vue, components/src/core/components/CardTable/Cell/Dropdown.vue, components/src/core/components/CardTable/Cell/dropdown.scss, components/src/core/components/CardTable/Cell/types.ts, components/src/core/components/CardTable/Table/table.scss, components/src/core/components/Form/Form.vue, components/src/core/components/InputField/InputField.vue, components/src/core/components/InputField/__tests__/input-field.spec.ts, components/src/utils/injectable.ts, components/src/utils/promiseDebounce.ts, storybook/package.json, storybook/stories/core/components/CardTable/CardTableLeavelist.story.vue, storybook/stories/core/components/CardTable/Table.stories.js, storybook/stories/core/components/Form/AsyncValidatableFrom.story.vue, storybook/stories/core/components/Form/DynamicValidatableFrom.story.vue, storybook/stories/core/components/Form/Form.stories.js, storybook/stories/core/components/Form/ValidatableFrom.story.vue, yarn.lock
- OHRM5X-480: oxd-form asynchronous validation added
- OHRM5X-528: oxd-cardtable dropdown action added
=> OHRM5X-480: OXD-Form asynchronous validation added

components/src/core/components/Input/MultiSelect/MultiSelectInput.vue, components/src/core/components/Input/Select/SelectDropdown.vue, components/src/core/components/Input/Select/SelectInput.vue, components/src/core/components/Input/Time/TimeInput.vue, storybook/stories/core/components/Input/SelectInput.stories.js
- OHRM5X-606: OXD-Time Input improve UX
- OHRM5X-609: OXD-Select Input enhancements on empty selector
=> OHRM5X-21: OXD-Time, OXD-Select Components Enhancements

.gitignore, scripts/build.js
https://classic.yarnpkg.com/en/docs/publishing-a-package/
```sh
node scripts/build.js
cd build
yarn login
yarn publish
```
=> Add oxd build script

components/src/core/components/Button/Icon.vue, components/src/core/components/Button/_mixins.scss, components/src/core/components/Button/_variables.scss, components/src/core/components/Button/icon.scss, components/src/core/components/Button/types.ts, components/src/core/components/Form/Form.vue, components/src/core/components/Input/DateInput.vue, components/src/core/components/Input/__tests__/date-input.spec.ts, storybook/stories/core/components/Button/Icon.stories.js
- OHRM5X-980: Add OXD-Datepicker display text prop
- OHRM5X-981: OXD-Icon button add theme colors
=> OHRM5X-980: OXD-Datepicker, OXD-Icon Button Improvements

components/src/core/components/Input/Select/SelectInput.vue, components/src/core/components/Input/__tests__/select-input.spec.ts, storybook/stories/core/components/Input/SelectInput.stories.js
Changes are done to support a condition to determine whether the default placeholder is shown or not
- Added a condition to show the default placeholder value (--select) when only required
- Updated stories file and added test scenario as well
=> RR-76  In Add New Report modal, there is an option as select which is unnecessary

components/src/core/components/Icon/icons.ts
=> RR-85  Size should be same for search box and new report button

components/src/core/components/Icon/icon.scss, components/src/core/components/Input/Autocomplete/QuickSearchInput.vue, components/src/core/components/Input/Autocomplete/autocomplete-input.scss, components/src/core/components/Input/_variables.scss
Following changes included in the commit
oxd-quick-search value not retain issue
oxd-quick-search styles update
auto complete style update
=> ENT-77 auto complete and quick search fixes

components/src/core/components/Input/Autocomplete/QuickSearchInput.vue
… options and add report modal options
=> RR-133  There is no padding and styles are not applied for both search options and add report modal options

components/src/core/components/Icon/icons.ts
this commit contains new icon addition for icons.
=> ENT- 226 add new icon for location

components/src/core/components/Icon/icon.scss, components/src/core/components/TableSidebar/TableSidebar.vue, components/src/core/components/TableSidebar/__tests__/TableSidebar.spec.ts, storybook/stories/core/components/List/list-config.json
- Fix icon sizes for svg icons in icon.scss
- Allow passing icon size for header action button (default to medium)
=> ENT - RMP-177

components/src/core/components/TableFilter/TableFilter.vue, components/src/core/components/TableFilter/table-filter.scss
Fixing Identified UI issues related to top filter button spacing
=> ENT- adding additional UI fixes related to button spacing

components/src/core/components/CardTable/Table/TableHeaderSortDropdown.vue
Fixing table sorting dropdown to autofocus the last selected sorting config on dropdown open by either Mouse Click or Keyboard Enter
=> ENT- Sorting Dropdown Keyboard accessibility fixes

components/src/core/components/CardTable/Cell/Actions.vue, components/src/core/components/CardTable/Cell/Dropdown.vue, components/src/core/components/CardTable/Cell/dropdown.scss, components/src/core/components/CardTable/Cell/types.ts, storybook/stories/core/components/CardTable/CardTableLeavelist.story.vue, storybook/stories/core/components/CardTable/Table.stories.js
Manually merged one commit from pull request #47 in orangehrm/oxd/ main branch.
https://github.com/orangehrm/oxd/pull/47/commits/0a37490b77ab068ba183a81ea1cabf6b1cca0170
=> ENT - OHRM5X-528: oxd-cardtable dropdown action added

components/src/core/components/CardTable/Cell/Dropdown.vue, components/src/core/components/CardTable/Cell/__tests__/__snapshots__/dropdown.spec.ts.snap, components/src/core/components/CardTable/Cell/__tests__/dropdown.spec.ts, components/src/core/components/CardTable/Cell/dropdown.scss, components/src/core/components/CardTable/Cell/types.ts
1.  Support optional icon to oxd-table-dropdown
2. style dropdown similar to oxd select dropdown
=> ENT - Support optional icon to oxd-table-dropdown,

components/src/core/components/CardTable/Cell/TableSelectInput.vue, components/src/core/components/CardTable/Cell/__tests__/__snapshots__/table-select-input.spec.ts.snap, components/src/core/components/CardTable/Cell/__tests__/table-select-input.spec.ts, components/src/core/components/CardTable/Cell/table-select-input.scss, components/src/core/components/Input/Select/SelectText.vue
Wrapping SelectInput and change styles for use within a List / Table.
=> ENT - wrapper for select input for use in list/table

components/src/core/components/CardTable/Cell/TableSelectInput.vue, components/src/core/components/CardTable/Cell/__tests__/__snapshots__/table-select-input.spec.ts.snap, components/src/core/components/CardTable/Cell/table-select-input.scss, components/src/core/components/Input/Select/SelectText.vue
This include some UI changes related to stage dropdown in the table
=> ENT - Stage Dropdown UI issue fixes

components/src/core/components/CardTable/Cell/table-select-input.scss, components/src/core/components/TableSidebar/table-left-panel.scss
Alignment issue fixes in left panel and stage dropdown
=> ENT - Adding style changes needed for alignment issues

components/src/core/components/List/List.vue, components/src/core/components/Pagination/Pagination.vue, components/src/core/components/Pagination/__tests__/__snapshots__/pagination.spec.ts.snap
* Hide next/previous buttons if there is only 1 page
* When changing number of items in the page, taking user into the 1st page
* set default page size to 20
=> RMP-191 Fixing pagination issues

components/src/core/components/List/types.ts
- Fixes to list configuration types
=> ENT - type fixes to list configuration related types

components/src/core/components/TableSidebar/table-left-panel.scss
Small UI issue fix in left panel cell when there is lengthy content
=> fix alignment issue in left panel when there is lengthy content

components/src/core/components/List/List.vue, components/src/core/components/Pagination/Pagination.vue
* Change pagination to 1st page if user clicks left pannel stage
* Change pagination from list component
=> [RMP-350] Change pagination to 1st page if user clicks left pannel stage

components/src/core/components/Button/Button.vue, components/src/core/components/Button/Icon.vue, components/src/core/components/Button/button.scss, components/src/core/components/CardTable/Cell/Dropdown.vue, components/src/core/components/CardTable/Cell/__tests__/dropdown.spec.ts, components/src/core/components/CardTable/Cell/__tests__/link-with-pill.spec.ts, components/src/core/components/CardTable/Table/TableHeaderSortDropdown.vue, components/src/core/components/Input/DateInput.vue, components/src/core/components/Input/Select/SelectInputButton.vue, components/src/core/components/Input/__tests__/quicksearch-input.spec..ts, components/src/core/components/Pagination/Pagination.vue, components/src/core/components/ProfilePic/types.ts, components/src/core/components/TableSidebar/TableSidebar.vue
Adding localization support for the left panel + Some lint issues.
=> ENT - Adding localization support for the left panel

changelog.md, components/src/core/components/Input/Autocomplete/AutocompleteInput.vue, components/src/core/components/List/List.vue
RMP-501, 502 and 503 related vue app changes [here](https://websvn.orangehrm.com/orangehrm?op=comp&compare[]=/enterprise/branch/recruitment-vue-conversion/@170909&compare[]=/enterprise/branch/recruitment-vue-conversion/@170910)
=> RMP-503 Added a prop to handle search key clearing on blur when addiing a button from outside via a slot

components/src/core/components/Calendar/CalendarController.vue, components/src/core/components/Input/Autocomplete/AutocompleteInput.vue, components/src/core/components/Input/Autocomplete/autocomplete-input.scss, components/src/core/components/Input/DateInput.vue, components/src/core/components/Input/DropdownInput.vue, components/src/core/components/Input/MultiSelect/MultiSelectInput.vue, components/src/core/components/Input/Select/SelectInput.vue, components/src/core/components/Input/Time/TimeInput.vue, components/src/core/components/List/List.vue, components/src/core/components/Pagination/Pagination.vue, components/src/directives/dropdown-direction/index.ts
Vue App changes related to this PR - https://websvn.orangehrm.com/orangehrm?op=comp&compare[]=/enterprise/branch/recruitment-vue-conversion/@171290&compare[]=/enterprise/branch/recruitment-vue-conversion/@171291
Apart from AutocompleteInput.vue and autocomplete-input.scss all the other files contains auto applied lint fixes
=> ENT - RMP-331 "Invalid validation message for autocomplete"

components/src/core/components/CardTable/Header/DefaultCardHeader.vue, components/src/core/components/CardTable/Table/TableHeaderSortDropdown.vue, components/src/core/components/CardTable/Table/table-header-sort-dropdown.scss, components/src/core/components/Input/Autocomplete/AutocompleteInput.vue, components/src/core/components/List/List.vue
Related vue app fixes
https://websvn.orangehrm.com/orangehrm?op=comp&compare[]=/enterprise/branch/recruitment-vue-conversion/@171404&compare[]=/enterprise/branch/recruitment-vue-conversion/@171405
=> ENT - RMP-472 - Localization doesn't support some strings in the candidate list

components/src/core/components/Input/Autocomplete/AutocompleteInput.vue
https://orangehrmenterprise.atlassian.net/browse/RMP-582
=> RMP-582 - bug fix

components/src/core/components/CardTable/Cell/__tests__/__snapshots__/dropdown.spec.ts.snap, components/src/core/components/DropdownMenu/DropdownMenu.vue, components/src/core/components/DropdownMenu/_variables.scss, components/src/core/components/DropdownMenu/dropdown-menu.scss, components/src/core/components/Input/Select/SelectInputButton.vue, components/src/core/components/Input/Select/select-input-button.scss, components/src/directives/dropdown-direction/index.ts, components/src/styles/_utility.scss, components/src/styles/_variables.scss
This PR contains the fixes for
https://orangehrmenterprise.atlassian.net/browse/RMP-460
=> ENT - RMP-460 - bug fix

components/src/composables/types.ts, components/src/composables/useField.ts, components/src/composables/useFormValidation.ts, components/src/core/components/Input/__tests__/input.spec.ts, components/src/core/components/InputField/InputField.vue, components/src/core/components/InputField/InputGroup.vue, components/src/core/components/Label/Label.vue, components/src/core/components/SchemaForm/SchemaForm.vue, storybook/stories/core/components/SchemaForm/SchemaForm.stories.js
This commit contains
Input Label Association support
Input Cross-Validation
Unit Test Update
=> ENG-8 Input widget modifications

components/src/core/components/Input/Autocomplete/AutocompleteInput.vue
This fix involves additional improvements for RMP-660/RMP-661
* support for special chars including $, Dot(.) etc.
* Unicode chars (tested with Sinhala)
* Case insensitive searches
=> ENT - Amendments for security fixes

components/src/core/components/Input/DateInput.vue
Adding localization support for Date Picker - Today, Clear ,Close
=> ENT - Issue RMP-525

components/src/core/components/List/list.scss
Set list table min height and removed pagination padding bottom as per the discussion with Mike
=> RMP-548 - set list table min height and removed pagination padding bottom

components/src/core/components/List/List.vue, components/src/core/components/List/list.scss
=> Add empty msg to oxd-list component

components/src/core/components/Grid/Grid.vue, components/src/core/components/Grid/grid-utility.scss
Cherry picked changes from commit 4dbd61c7676a746e9f15312b629cc2899d20b68d in main branch.
=> oxd-grid utility classes added. 

components/src/core/components/Input/_variables.scss, components/src/core/components/Input/switch-input.scss
Styling for disabled off switch based on Mike's feedback.
These styles are not given yet in the oxd guide.
=> styles for disabled off switch

components/src/core/components/Input/Autocomplete/AutocompleteInput.vue
Reverting changes related to autocpmplete component in https://github.com/orangehrm/oxd/pull/321
=> revert lib changes for RMP-435

components/src/core/components/Icon/_variables.scss, components/src/core/components/Icon/help-popup-icon.scss, components/src/core/components/InputField/_variables.scss
* Introduced scss variables for help popup icon styling
* Styling changes to match oxd.
=> Help text styling

components/src/core/components/CardTable/Header/DefaultCardHeader.vue, components/src/core/components/CardTable/Table/TableHeaderSortDropdown.vue, components/src/core/components/Input/Autocomplete/AutocompleteInput.vue
Fixes errors in storybook due to missing $t
=> Replace usages of $t with translateMixin

components/src/core/components/Input/Select/SelectText.vue, components/src/core/components/Input/Select/select-input.scss, components/src/core/components/Input/__tests__/__snapshots__/multiselect-input.spec.ts.snap, components/src/core/components/Input/__tests__/__snapshots__/select-input.spec.ts.snap, components/src/core/components/Input/__tests__/select-input.spec.ts, components/src/core/components/Pagination/__tests__/__snapshots__/pagination.spec.ts.snap, storybook/stories/core/components/Input/SelectInput.stories.js, storybook/stories/core/components/Input/SelectInputAfterSelect.story.vue, storybook/stories/core/components/Input/SelectInputEvents.story.vue
This commit contains
oxd-select storybook updates
label select associate update
=> Ent-7 Oxd select

components/.eslintrc.js, components/src/core/components/Calendar/CalendarController.vue, components/src/core/components/Calendar/CalendarDropdown.vue, components/src/core/components/Calendar/__tests__/__snapshots__/calendar-controller.spec.ts.snap, components/src/core/components/Calendar/__tests__/__snapshots__/calendar.spec.ts.snap, components/src/core/components/Calendar/__tests__/calendar-controller.spec.ts, components/src/core/components/Calendar/calendar-dropdown.scss, components/src/core/components/Calendar/calendar.scss, components/src/core/components/Calendar/types.ts, components/src/core/components/CardTable/CardTable.vue, components/src/core/components/CardTable/Header/DefaultCardHeader.vue, components/src/core/components/CardTable/__tests__/table-header-sort-drop-down.spec.ts, components/src/core/components/CardTable/types.ts, components/src/core/components/Icon/icons.ts, components/src/core/components/Input/Autocomplete/AutocompleteInput.vue, components/src/core/components/Input/CheckboxInput.vue, components/src/core/components/Input/DateInput.vue, components/src/core/components/Input/Select/SelectInputButton.vue, components/src/core/components/Input/__tests__/__snapshots__/date-input.spec.ts.snap, components/src/core/components/Input/__tests__/switch-input.spec.ts, components/src/core/components/Input/date-input.scss, components/src/core/components/InputField/InputField.vue, components/src/core/components/List/List.vue, components/src/core/components/List/__tests__/list.spec.ts, components/src/core/components/SchemaForm/SchemaForm.vue, components/src/core/components/SchemaForm/types.ts, components/src/core/components/TableSidebar/TableSidebar.vue, components/src/core/components/TableSidebar/__tests__/TableSidebar.spec.ts, components/src/directives/focus-first-element/index.ts, components/src/validation/rules.ts
Apart from the below files all the other files have been updated due the execution of "yarn lint" automatic lint fixes
components/src/core/components/Calendar/CalendarController.vue
components/src/core/components/Calendar/CalendarDropdown.vue
components/src/core/components/Calendar/__tests__/__snapshots__/calendar-controller.spec.ts.snap
components/src/core/components/Calendar/__tests__/__snapshots__/calendar.spec.ts.snap
components/src/core/components/Calendar/__tests__/calendar-controller.spec.ts
components/src/core/components/Calendar/calendar-dropdown.scss
components/src/core/components/Calendar/calendar.scss
components/src/core/components/Calendar/types.ts
=> ENT - RMP-576 - Calendar component UI fixes

changelog.md, components/src/core/components/Divider/Divider.vue, components/src/core/components/Divider/__tests__/__snapshots__/divider.spec.ts.snap
- [ Done] Test Coverage is 100% for the newly added code
- [ Done] Storybook stories are added/updated for the changed areas
- [ Done ] Components standards defined [in this document](https://docs.google.com/document/d/16_Nd3VxE_lTD9pVkONQ0egn7IiwyX1pVXZjzl-V4tU8/) are followed
- [ Done] Code is linted properly
- [ Done] Developer testing is done for the affected areas
- [ N/A] Package version updated (not applicable to ent branch)
- [Done ] Changelog.md updated on possible breaking (applicable to ent branch)
=> Divider issue fixes

components/src/core/components/Input/MultiSelect/MultiSelectChips.vue, components/src/core/components/Input/Select/SelectText.vue, components/src/core/components/Input/Select/select-input.scss, components/src/core/components/Input/__tests__/multiselect-input.spec.ts, storybook/stories/core/components/Input/MultiSelectInput.stories.js, storybook/stories/core/components/Input/MultiSelectInputAfterSelect.story.vue, storybook/stories/core/components/Input/MultiSelectInputEvents.story.vue, storybook/stories/core/components/SchemaForm/SchemaForm.stories.js
This commit contains oxd-multi-select stories updates and unit test updates.
=> Ent-10 Oxd multi select

storybook/stories/core/components/Icon/HelpPopupIcon.stories.js
Correct the Group of the HelpPopup story
=> Correct the Group of the story

components/src/core/components/Divider/Divider.vue, components/src/core/components/Divider/__tests__/__snapshots__/divider.spec.ts.snap
- [Done] Test Coverage is 100% for the newly added code
- [Done] Storybook stories are added/updated for the changed areas
- [Done] Components standards defined [in this document](https://docs.google.com/document/d/16_Nd3VxE_lTD9pVkONQ0egn7IiwyX1pVXZjzl-V4tU8/) are followed
- [Done] Code is linted properly
- [Done] Developer testing is done for the affected areas
- [N/A] Package version updated (not applicable to ent branch)
- [N/A] Changelog.md updated on possible breaking (applicable to ent branch)
=> fix for the reports list issue due to divider changes

components/src/core/components/Input/MultiSelect/MultiSelectChips.vue, components/src/core/components/Input/MultiSelect/MultiSelectInput.vue, components/src/core/components/Input/MultiSelect/multiselect-input.scss, components/src/core/components/Input/Select/SelectText.vue, components/src/core/components/Input/Select/select-input.scss, components/src/core/components/Input/__tests__/__snapshots__/multiselect-input.spec.ts.snap, components/src/core/components/Input/__tests__/__snapshots__/select-input.spec.ts.snap, components/src/core/components/Input/__tests__/multiselect-input.spec.ts, storybook/stories/core/components/Input/MultiSelectInput.stories.js, storybook/stories/core/components/Input/MultiSelectInputAfterSelect.story.vue, storybook/stories/core/components/Input/MultiSelectInputEvents.story.vue, storybook/stories/core/components/SchemaForm/SchemaForm.stories.js
This commit contains
1) SelectText component style fix
2) keyboard access support for chips in multi-select
=> END- 10 Oxd multi select improvments

components/src/core/components/CardTable/Cell/table-select-input.scss
This should merge to ent branch not ent-dev. therefore removing the code changes from ent-dev and creating another PR ent with a new branch which is created from ent branch
=> ENT - RMP-541 - remove from ent-dev

components/src/core/components/CardTable/Cell/table-select-input.scss
This should merge to ent branch not ent-dev. therefore created another PR to ent-dev to by removing the changes and creating this PR get the changes into ent branch
=> ENT - RMP-541 - get into ent - removed the fix from ent-dev and moving to ent

components/src/core/components/Divider/__tests__/__snapshots__/divider.spec.ts.snap, components/src/core/components/Input/Autocomplete/AutocompleteChips.vue, components/src/core/components/Input/Autocomplete/AutocompleteInput.vue, components/src/core/components/Input/Autocomplete/AutocompleteTextInput.vue, components/src/core/components/Input/Autocomplete/autocomplete-input.scss, components/src/core/components/Input/MultiSelect/multiselect-input.scss, components/src/core/components/Input/__tests__/__snapshots__/autocomplete-input.spec.ts.snap, components/src/core/components/Input/__tests__/__snapshots__/quicksearch-input.spec..ts.snap, components/src/core/components/Input/__tests__/autocomplete-input.spec.ts, storybook/stories/core/components/Input/AutoCompleteEvents.story.vue, storybook/stories/core/components/Input/AutocompleteInput.stories.js, storybook/stories/core/components/Input/QuickSearch.stories.js, storybook/stories/core/components/SchemaForm/SchemaForm.stories.js
This commit contains
AutoComplete fix on read-only mode and style update
StoryBook Update
Unit Tests Update
=> ENG-9 auto complete improvements

components/src/core/components/CardTable/Table/TableHeaderSortDropdown.vue, components/src/core/components/Input/DateInput.vue
Issue,
https://orangehrmenterprise.atlassian.net/browse/RMP-576?focusedCommentId=16655
Solution,
Blurred date picker trigger button's focus state after selecting a date and focused date picker text input field.
=> ENT - RMP-576 - reopened bug fix

components/src/core/components/List/List.vue, components/src/core/components/List/list.scss, components/src/styles/_utility.scss
=> ENT - RMP-718 - Browser specific broken issue fix for

components/src/core/components/Input/Select/SelectInput.vue, components/src/core/components/Input/Select/SelectText.vue
This commit contains the fix for blur event on Select Text Input.
@Super-Chama @lgtkaushalya .
=> ENG-16 select bug fix

components/src/core/components/Tabs/Tabs.vue, components/src/core/components/Tabs/__tests__/__snapshots__/tabs.spec.ts.snap, components/src/core/components/Tabs/__tests__/tabs.spec.ts, components/src/core/components/Tabs/tabs.scss, components/src/core/components/Tabs/types.ts, storybook/stories/core/components/Tabs/Tabs.stories.js, storybook/stories/core/components/Tabs/TabsEvents.story.vue
=> Tab component

changelog.md, components/src/core/components/Input/input.scss
=> Rmp 686 image shape changes

components/src/core/components/InfoBox/InfoBox.vue, components/src/core/components/InfoBox/__tests__/__snapshots__/info-box.spec.ts.snap, components/src/core/components/InfoBox/__tests__/info-box.spec.ts, components/src/core/components/InfoBox/_variables.scss, components/src/core/components/InfoBox/info-box.scss, storybook/stories/core/components/InfoBox/InfoBox.stories.js
1. Increased font-size.
2. Replaced hardcoded values with css variables.
3. Introduced title line-height and wrapper height props
4. Updated tests and the storybook accordingly..
=> ENT - RMP-685 - UI Improvements of Info box

components/package.json, components/src/core/components/Dialog/Dialog.vue, components/src/core/components/Dialog/__tests__/__snapshots__/dialog.spec.ts.snap, components/src/core/components/Dialog/_variables.scss, components/src/core/components/Dialog/close-button.scss, components/src/core/components/Dialog/dialog.scss, components/src/core/components/Form/form.scss, components/src/core/components/Grid/GridItem.vue, components/src/core/components/Grid/_variables.scss, components/src/core/components/Grid/grid-item.scss, components/src/core/components/Grid/grid.scss, components/src/core/components/Sheet/_variables.scss, components/src/core/components/TableFilter/TableFilter.vue, components/src/core/components/TableFilter/_variables.scss, components/src/core/components/TableFilter/table-filter.scss, components/src/core/components/Text/_variables.scss, components/src/core/components/Text/text.scss, components/src/core/components/Text/types.ts, package.json, storybook/stories/core/components/Dialog/DialogDeleteConfirmation.story.vue, storybook/stories/core/components/Form/AddJobTitle.story.vue, storybook/stories/core/components/Grid/Grid.stories.js, storybook/stories/core/components/Grid/Grid.story.vue, storybook/stories/core/components/TableFilter/TableFilter.story.vue
=> OHRM5X-377: OXD Library enhancements / general defect fixes

components/src/core/components/Input/Input.vue, components/src/core/components/Input/__tests__/__snapshots__/date-input.spec.ts.snap, components/src/core/components/Input/__tests__/__snapshots__/input.spec.ts.snap, components/src/core/components/Input/__tests__/__snapshots__/password-input.spec.ts.snap, components/src/core/components/Input/__tests__/__snapshots__/time-input.spec.ts.snap, components/src/core/components/Input/input.scss, components/src/core/components/InputField/__tests__/__snapshots__/input-field.spec.ts.snap
=> date inpur issue fixed

components/src/core/components/CardTable/Table/table.scss, components/src/core/components/List/List.vue, components/src/core/components/List/list.scss
I have fixed 1st 2nd and 3rd scenarios of the below reported defect and the 4th scenario will be fixed by Thilina as it's related to one of his changes in select inputs
[https://orangehrmenterprise.atlassian.net/browse/RMP-720](https://orangehrmenterprise.atlassian.net/browse/RMP-720)
=> ENT - RMP-720 - Bug fixes

changelog.md, components/src/core/components/List/list.scss
Fix no data found icon position in list component
=> Fix no data found icon position in list component

components/src/core/components/Input/Autocomplete/AutocompleteInput.vue, components/src/core/components/Input/__tests__/autocomplete-input.spec.ts, storybook/stories/core/components/Input/AutocompleteInput.stories.js
=> Adding changes related to RMP-677

components/src/core/components/InputField/_variables.scss, components/src/core/components/InputField/input-field.scss
=> add top margin to input field hint

components/src/core/components/List/List.vue, components/src/core/components/Pagination/Pagination.vue, components/src/core/components/Pagination/__tests__/__snapshots__/pagination.spec.ts.snap, components/src/core/components/Pagination/__tests__/pagination.spec.ts
=> ENT - RMP-709 - bug fix

storybook/stories/core/components/Input/Input.stories.js
This commit contains storybook documentation update for Input Widget
=> input story incorrect documentation  update

components/package.json, components/src/core/components/Grid/_variables.scss, components/src/core/components/Grid/grid.scss, components/src/core/components/Input/Autocomplete/AutocompleteInput.vue, components/src/core/components/Input/__tests__/autocomplete-input.spec.ts, package.json, storybook/stories/core/components/Grid/Grid.story.vue
=> OHRM5X-320: OXD general defect fixes

storybook/stories/core/components/Input/PasswordInput.stories.js, storybook/stories/core/components/Input/PasswordInputEvents.story.vue
This commit contains storybook documentation update for password Input Component
=> ENG-23 password input stories update

components/src/core/components/Form/Form.vue, components/src/directives/focus-first-element/index.ts
This commit contains the fix for schema form the first element not focus
=> ENG-23 fix in schema form element focus

changelog.md, components/src/core/components/Alert/Alert.vue, components/src/core/components/Alert/__tests__/alert.spec.ts, components/src/core/components/Alert/_variables.scss, components/src/core/components/Alert/alert.scss, components/src/core/components/CardTable/Table/table.scss, components/src/core/components/Form/Form.vue, components/src/core/components/Input/DateInput.vue, components/src/core/components/Input/RadioInput.vue, components/src/core/components/Input/Select/SelectText.vue, components/src/core/components/Input/Select/select-input.scss, components/src/core/components/Input/__tests__/__snapshots__/multiselect-input.spec.ts.snap, components/src/core/components/Input/__tests__/__snapshots__/select-input.spec.ts.snap, components/src/core/components/Input/__tests__/date-input.spec.ts, components/src/core/components/Input/__tests__/radio-input.spec.ts, components/src/core/components/Input/_variables.scss, components/src/core/components/Input/radio-input.scss, components/src/core/components/Input/switch-input.scss, components/src/core/components/InputField/_variables.scss, components/src/core/components/InputField/input-field.scss, components/src/core/components/List/List.vue, components/src/core/components/List/list.scss, components/src/core/components/Pagination/Pagination.vue, components/src/core/components/Pagination/__tests__/__snapshots__/pagination.spec.ts.snap, components/src/core/components/Pagination/__tests__/pagination.spec.ts, components/src/core/components/SchemaForm/types.ts, components/src/directives/focus-first-element/index.ts, components/src/styles/_variables.scss, storybook/stories/core/components/Alert/Alert.stories.js, storybook/stories/core/components/Input/Input.stories.js
=> Merge of ent to ent-dev

components/src/core/components/Dialog/Dialog.vue
=> LMR-198 key board escape close modal improvement  for dialog

components/src/core/components/Dialog/Dialog.vue, components/src/directives/focus-trap/index.ts
This commit contains fix for focus-trap directive
=> ENG-30 Focus trap

components/src/core/components/Dialog/Dialog.vue
=> Dialog improvement on key.esc

changelog.md, components/src/core/components/Input/__tests__/__snapshots__/checkbox-group.spec.ts.snap, components/src/core/components/InputField/InputField.vue, components/src/core/components/InputField/InputGroup.vue, components/src/core/components/InputField/__tests__/__snapshots__/input-field.spec.ts.snap, components/src/core/components/InputField/__tests__/input-field.spec.ts, components/src/core/components/InputField/_variables.scss, components/src/core/components/InputField/input-field.scss, components/src/core/components/InputField/input-group.scss, components/src/core/components/InputField/types.ts, components/src/core/components/SchemaForm/SchemaForm.vue, components/src/core/components/SchemaForm/types.ts, storybook/stories/core/components/Input/Input.stories.js, storybook/stories/core/components/InputField/InputField.stories.js
=> Refactoring Hint and Label help text

components/src/core/components/Dialog/Dialog.vue, components/src/directives/focus-trap/index.ts
=> Dialog improvement on escape key

components/src/core/components/Dialog/Dialog.vue
=> dialog esc improement

components/src/core/components/Dialog/Dialog.vue
=> Dialog esc key event fix

components/src/core/components/Input/__tests__/__snapshots__/input.spec.ts.snap
=> snap shot failure fix

components/package.json, components/src/composables/__tests__/useResponsive.spec.ts, components/src/composables/useResponsive.ts, package.json
=> OHRM5X-1491: Improve useResponsive composable

components/src/core/components/InfoBox/info-box.scss
=> ENT - RMP-745 - Candidate Profile - "Job Title" and "Date of Application" tiles are clickable

components/src/core/components/CardTable/Header/DefaultCardHeader.vue
=> list table header checkbox fix

components/src/core/components/Input/CheckboxGroup.vue, components/src/core/components/Input/__tests__/checkbox-group.spec.ts, storybook/stories/core/components/Input/CheckboxGroup.stories.js
=> ENG- 20 Checkbox group individual style and auto-focus support addition

components/src/core/components/InfoBox/info-box.scss
=> ENT - RMP-745 - Added the misssing "!important" to css

components/src/core/components/Input/SwitchInput.vue, components/src/core/components/Input/__tests__/__snapshots__/switch-input.spec.ts.snap, components/src/core/components/Input/__tests__/switch-input.spec.ts, components/src/core/components/Input/_variables.scss, components/src/core/components/Input/switch-input.scss, storybook/stories/core/components/Input/CheckboxInputEvents.story.vue, storybook/stories/core/components/Input/SwitchInput.stories.js, storybook/stories/core/components/Input/SwitchInputEvents.story.vue, storybook/stories/core/components/SchemaForm/SchemaForm.stories.js
=> ENG-26 Switch input  widget improvements

components/src/core/components/TableSidebar/TableSidebar.vue
=> [ENT] - Add Support to Disable Add Button in List Side panel

components/src/core/components/Input/__tests__/date-input.spec.ts
=> Date input unit test fail fix

components/src/core/components/Input/DateInput.vue
=> fix date typing issue

components/src/core/components/CardTable/Cell/__tests__/__snapshots__/table-select-input.spec.ts.snap, components/src/core/components/InfoBox/__tests__/info-box.spec.ts, components/src/core/components/Input/Select/SelectInput.vue, components/src/core/components/Input/Select/SelectText.vue, components/src/core/components/Input/Select/select-input.scss, components/src/core/components/Input/__tests__/__snapshots__/multiselect-input.spec.ts.snap, components/src/core/components/Input/__tests__/__snapshots__/select-input.spec.ts.snap, components/src/core/components/Input/__tests__/select-input.spec.ts, components/src/core/components/Pagination/__tests__/__snapshots__/pagination.spec.ts.snap, components/src/core/components/Pagination/__tests__/pagination.spec.ts, storybook/stories/core/components/Input/SelectInput.stories.js
=> ENG-51 select improvements

components/package.json, components/src/composables/useField.ts, components/src/core/components/Grid/_variables.scss, components/src/core/components/Grid/grid.scss, components/src/core/components/InputField/InputField.vue, package.json, storybook/stories/core/components/Form/DisableValidationForm.story.vue, storybook/stories/core/components/Form/Form.stories.js
=> OHRM5X-1586: OXD Form prevent validation of disabled fields

changelog.md, components/src/core/components/CardTable/Table/table.scss, components/src/core/components/List/list.scss
=> Add css changes to List

changelog.md, components/src/core/components/Input/Time/TimeInput.vue, components/src/core/components/Input/Time/TimePicker.vue, components/src/core/components/Input/Time/time-input.scss, components/src/core/components/Input/Time/time-picker.scss, components/src/core/components/Input/__tests__/__snapshots__/time-input.spec.ts.snap, components/src/core/components/Input/__tests__/time-input.spec.ts, components/src/core/components/Input/_variables.scss
- Style changes
- New AM/PM toggle in the input.
- Click outside behavior
- Focus trap behavior
- Usability and keyboard access improvements to time picker
=> Improvements to Time Input

components/src/core/components/BulletPoints/BulletPoints.scss, components/src/core/components/BulletPoints/BulletPoints.vue, components/src/core/components/BulletPoints/__tests__/__snapshots__/bullet-points.spec.ts.snap, components/src/core/components/BulletPoints/__tests__/bullet-points.spec.ts, components/src/core/components/BulletPoints/_variables.scss, components/src/core/components/BulletPoints/types.ts, components/src/core/components/Collapsible/Collapsible.scss, components/src/core/components/Collapsible/Collapsible.vue, components/src/core/components/Collapsible/__tests__/__snapshots__/collapsible.spec.ts.snap, components/src/core/components/Collapsible/__tests__/collapsible.spec.ts, components/src/core/components/Collapsible/_variables.scss, storybook/stories/core/components/BulletPoints/BulletPoints.stories.js, storybook/stories/core/components/Collapsible/Collapsible.stories.js, storybook/stories/core/components/Collapsible/CollapsibleEvents.story.vue
=> collapsible component and the bullet points added

components/package.json, components/src/core/components/Input/DateInput.vue, components/src/core/components/Input/__tests__/date-input.spec.ts, components/src/utils/date.ts, package.json
=> OHRM5X-1588: OXD date input allow invalid date format input

components/src/core/components/Calendar/Calendar.vue, components/src/core/components/Calendar/Date.vue, components/src/core/components/Calendar/_variables.scss, components/src/core/components/Calendar/calendar.scss, components/src/core/components/Input/DateInput.vue, storybook/stories/core/components/Input/Date.stories.js
=> ENG-44 date input disable feature

components/src/core/components/Input/Time/TimeInput.vue, components/src/core/components/Input/__tests__/time-input.spec.ts
=> Fix for TimePicker's AM/PM not getting changed when AM/PM toggled in TimeInput

components/src/directives/focus-first-element/index.ts
This commit contains a fix applied for track async element updates on for focus-first directive
=> ENG-39 focus directive update

components/src/core/components/Input/Time/time-input.scss, components/src/core/components/Input/_variables.scss
=> Position AM/PM label to right of TimeInput

components/src/core/components/ProgressCircle/ProgressCircle.scss, components/src/core/components/ProgressCircle/ProgressCircle.vue, components/src/core/components/ProgressCircle/__tests__/ProgressCircle.spec.ts, components/src/core/components/ProgressCircle/__tests__/__snapshots__/ProgressCircle.spec.ts.snap, components/src/core/components/ProgressCircle/_variables.scss, storybook/stories/core/components/ProgressCircle/ProgressCircle.stories.js
=> ProgressCircle Component added

components/src/core/components/InfoBox/info-box.scss, storybook/stories/core/components/InfoBox/InfoBox.stories.js
Wrapped the texts of the label of the Info Box component  when it doesn't have spaces between
=> ENT - RMP-785 - bug fix

changelog.md, components/src/core/components/CardTable/Cell/actions.scss, components/src/core/components/List/list.scss
=> List css changes

components/src/directives/focus-first-element/index.ts
Fix the issue on directive instances overriding same values on comparison.
=> ENG-39 fix directive data sharing among multiple instances

components/src/core/components/Calendar/Date.vue
This commit contains removing the disabled dates tab focus support
=> ENG-44 remove disabled dates  tab focus

changelog.md, components/src/core/components/Table/ClassicTable.vue, components/src/core/components/Table/classic-table.scss, storybook/stories/core/components/Table/ClassicTable.story.vue
=> Fixing column widths in oxd-classic-table

components/src/core/components/List/List.vue, components/src/core/components/List/__tests__/list-minimal.json, components/src/core/components/List/__tests__/list.spec.ts, storybook/stories/core/components/List/list-with-sidebar/top-bar.table.list.ts
=> list quick search related improvements

components/src/core/components/Input/DateInput.vue
This commit contains a fix related to tab focus in the date-picker
=> ENG-54 Datepicker focus issue fix

components/src/core/components/ProgressCircle/ProgressCircle.vue, components/src/core/components/ProgressCircle/__tests__/ProgressCircle.spec.ts, storybook/stories/core/components/ProgressCircle/ProgressCircle.stories.js
=> prop name change discussed in the UI discussion

components/src/core/components/Input/RadioPills/RadioPill.vue, components/src/core/components/Input/RadioPills/RadioPillGroup.vue, components/src/core/components/Input/RadioPills/radio-pill-group.scss, components/src/core/components/Input/RadioPills/radio-pill.scss, components/src/core/components/Input/__tests__/radio-pill-group.spec.ts, components/src/core/components/Input/__tests__/radio-pill.spec.ts, components/src/core/components/Input/_variables.scss, components/src/styles/_variables.scss, storybook/stories/core/components/Input/RadioPillGroup.stories.js
=> RadioPillGroup Component

changelog.md, components/src/core/components/Table/ClassicTable.vue, components/src/core/components/Table/__tests__/__snapshots__/classic-table.spec.ts.snap, components/src/core/components/Table/__tests__/classic-table.spec.ts, storybook/stories/core/components/Table/ClassicTable.story.vue
=> Classic Table - Add support for tooltips and rendering styled contents

components/src/core/components/Input/Time/TimeInput.vue, components/src/core/components/Input/Time/TimePicker.vue, components/src/core/components/Input/Time/time-input.scss, components/src/core/components/Input/__tests__/time-input.spec.ts
=> LMR-239 time picker fixes

changelog.md, components/src/styles/_utility.scss
=> oxd tooltip - fix the broken scenario of the tooltip due to PR #488

changelog.md, components/src/core/components/Input/RadioPills/RadioPillGroup.vue, components/src/core/components/Input/RadioPills/radio-pill-group.scss, components/src/core/components/InputField/InputField.vue, components/src/core/components/InputField/types.ts, storybook/stories/core/components/Input/RadioPillGroup.stories.js, storybook/stories/core/components/SchemaForm/SchemaForm.stories.js
=> Radio pills input field support

changelog.md, components/src/core/components/Icon/icons.ts
=> Change fill colour of oxd-add icon

components/package.json, components/src/core/components/CardTable/Table/_variables.scss, components/src/core/components/CardTable/Table/table-row.scss, components/src/core/components/Input/Autocomplete/AutocompleteInput.vue, components/src/core/components/Input/__tests__/autocomplete-input.spec.ts, package.json
=> OHRM5X-966: OXD Autocomplete support pass through search term

storybook/stories/core/components/Icon/Icon.stories.js
=> added a story showing all icons in icons.ts

components/src/core/components/Input/Time/TimePicker.vue, components/src/core/components/Input/__tests__/time-input.spec.ts
=> Time Picker event behaviour switch

components/src/core/components/PopOver/PopOver.vue, components/src/core/components/PopOver/__tests__/__snapshots__/pop-over.spec.ts.snap, components/src/core/components/PopOver/__tests__/pop-over.spec.ts, components/src/core/components/PopOver/pop-over.scss, components/src/directives/popover-direction/index.ts, storybook/stories/core/components/PopOver/PopOver.stories.js, storybook/stories/core/components/PopOver/PopOver.story.vue, storybook/stories/core/components/PopOver/PopOverRightAligned.story.vue
=> PopOver Draft

components/src/core/components/Comments/Comment.vue, components/src/core/components/Comments/CommentBox.vue, components/src/core/components/Comments/Comments.vue, components/src/core/components/Comments/comment.scss, components/src/core/components/SchemaForm/types.ts, storybook/stories/core/components/Comments/Comments.stories.js
=> ENT - RMP-699 - UI improvements

components/src/core/components/List/List.vue
=> List tableFilterAdditionalSingleActions added

components/src/core/components/Comments/Comment.vue, components/src/core/components/Comments/CommentBox.vue, components/src/core/components/Comments/Comments.vue, components/src/core/components/Comments/comments.scss, storybook/stories/core/components/Comments/Comments.stories.js
=> ENT - RMP-699 - Comments component improvements

components/src/core/components/Comments/Comment.vue, components/src/core/components/Comments/Comments.vue, components/src/core/components/Comments/comment.scss
=> ENT - RMP-699 - Comments component UI improvements

components/src/core/components/Input/Time/TimePicker.vue, components/src/core/components/Input/__tests__/time-input.spec.ts
=> LMR-276 timepicker  2 digits number typing issue fix

components/src/core/components/Comments/Comment.vue, components/src/core/components/Comments/comment.scss
=> ENT - RMP-699

components/src/core/components/Comments/Comment.vue, components/src/core/components/Comments/Comments.vue
=> ENT - RMP-699 - comment component validation issue fixes

components/src/core/components/Input/RadioGroup.vue, components/src/core/components/Input/__tests__/__snapshots__/radio-group.spec.ts.snap, components/src/core/components/Input/__tests__/radio-group.spec.ts, components/src/core/components/InputField/InputField.vue, components/src/core/components/InputField/types.ts, storybook/stories/core/components/Input/RadioGroup.stories.js, storybook/stories/core/components/Input/RadioGroup.story.vue, storybook/stories/core/components/Input/RadioGroupEvents.story.vue
=> Implement radio group component

components/src/core/components/Table/ClassicTable.vue, components/src/core/components/Table/__tests__/__snapshots__/classic-table.spec.ts.snap, components/src/core/components/Table/table-row.scss
=> LMR-287 classic table keyboard accessibility adding

components/src/core/components/Input/Time/TimeInput.vue
=> LMR-282 fix time picker initial value set to empty

changelog.md, components/src/core/components/Input/Time/TimeInput.vue, components/src/core/components/Input/__tests__/__snapshots__/time-input.spec.ts.snap, components/src/core/components/Input/__tests__/time-input.spec.ts, storybook/stories/core/components/Input/Time.stories.js
=> ENT - RMP - time picker improvements and modelValue setting issue

components/src/core/components/Comments/Comments.vue
=> ENT - RMP-699 Comment box improvements

components/src/core/components/Comments/CommentBox.vue, components/src/core/components/Comments/Comments.vue, storybook/stories/core/components/Comments/Comments.stories.js
=> RMP-699 - Added prop to hide add comment section

components/src/core/components/Segments/Segments.vue, components/src/core/components/Segments/__tests__/__snapshots__/segments.spec.ts.snap, components/src/core/components/Segments/__tests__/segments.spec.ts, components/src/core/components/Segments/segments.scss, components/src/core/components/Segments/types.ts, storybook/stories/core/components/Segments/SegmentEvents.story.vue, storybook/stories/core/components/Segments/Segments.stories.js, storybook/stories/core/components/Segments/Segments.story.vue
=> Implement oxd segment component (credit goes to gayan)

components/src/core/components/Input/Time/TimeInput.vue, components/src/core/components/Input/__tests__/time-input.spec.ts
=> ENT - Time Input improvements to set HH:MM placeholder in the initial rendering

components/src/core/components/Comments/Comments.vue, storybook/stories/core/components/Comments/Comments.stories.js
=> ENT - RMP-673 - improvements

components/src/core/components/Comments/Comments.vue, storybook/stories/core/components/Comments/Comments.stories.js
=> ENT - RMP - changed commentThreadMinHeight from number to string

components/src/core/components/Input/TreeSelect/TreeSelect.vue, components/src/core/components/Input/TreeSelect/tree-select-input.scss, components/src/core/components/Input/TreeSelect/type.ts, components/src/core/components/InputField/InputField.vue, components/src/core/components/InputField/types.ts, storybook/stories/core/components/treeSelect/TreeSelect.story.vue
=> Improved keyboard accessibility

components/src/core/components/Input/FileInput.vue
=> Rmp696 filedownloadbox corrections

components/src/core/components/Calendar/_variables.scss
=> LMR-299 oxd colour update for calendar half holiday

components/src/core/components/Calendar/calendar.scss
=> LMR-399 weekend style update

components/src/core/components/Comments/comment.scss
=> style modification for commentor name  and the hint

components/src/core/components/Comments/comment-box.scss
=> Fix comment box color issue

components/src/core/components/Comments/_variables.scss, components/src/core/components/Comments/comments.scss
=> margin styles added

components/src/core/components/Comments/comment.scss
=> Fix new line preservation RMP 875

components/src/core/components/Input/TreeSelect/TreeSelect.vue, components/src/core/components/Input/TreeSelect/tree-select-input.scss, storybook/stories/core/components/treeSelect/TreeSelect.story.vue
=> Tree select3

components/src/core/components/Input/FileInput.vue
=> update mode issue fixed

changelog.md, components/src/core/components/Input/RadioPills/RadioPill.vue, components/src/core/components/Input/RadioPills/radio-pill.scss
=> Radio pills - set tab focus colour and setting name prop for the pills

components/src/core/components/List/List.vue, components/src/core/components/List/list.scss
=> Fix broken RMP 814 - left pannel padding issue

components/src/core/components/Input/checkbox-input.scss, components/src/core/components/Input/radio-input.scss
=> Rmp 863 UI issues correction

components/src/core/components/Comments/Comment.vue
=> ENT - RMP-850 - initial comment content is not getting updated when confirmed the update

changelog.md, components/src/core/components/Input/Time/TimePicker.vue
=> Fix LMR-435. Hour input picking value from minute

components/src/core/components/Input/TreeSelect/tree-select-input.scss
=> added horizontal scroll when content width overflows

components/src/directives/focus-first-element/index.ts
=> RR2-388 - fix in focus-first directive

components/src/core/components/Input/Select/navigation-mixin.ts
=> RR2-388 fix on pointer

components/src/core/components/Input/date-input.scss
=> RMP-895 date picker style fix

components/src/core/components/List/list.scss
=> LMR-325 fix in oxd-list

components/src/core/components/PopOver/PopOver.vue
=> popover modal keyboard accessibility fixes

components/src/core/components/Input/Select/select-input.scss
=> RMP-889 select option border bottom remove

changelog.md, components/src/core/components/Input/Select/select-input-button.scss
=> RMP-889-fix-in-select-button-style

components/src/core/components/InfoBox/info-box.scss
=> style update in info box

changelog.md, components/src/core/components/Input/MultiSelect/MultiSelectChips.vue, components/src/core/components/Input/MultiSelect/MultiSelectInput.vue, storybook/stories/core/components/Input/MultiSelectInput.stories.js, storybook/stories/core/components/Input/MultiSelectInputCustomChips.story.vue
=> Add a custom template to multiselect-chips

components/src/core/components/Comments/Comment.vue, components/src/core/components/Comments/Comments.vue
=> RMP-894 - comments were able to update when the lengthy characters validation exists

changelog.md, components/src/core/components/Input/Autocomplete/AutocompleteChips.vue, components/src/core/components/Input/Autocomplete/AutocompleteInput.vue, storybook/stories/core/components/Input/AutocompleteCustomChips.story.vue, storybook/stories/core/components/Input/AutocompleteInput.stories.js
=> Support custom templates in autocomplete-chips

components/src/core/components/Input/checkbox-input.scss
=> RMP-892 fix default selected disabled checkbox style

components/src/core/components/Comments/Comments.vue
=> RMP-894 - cannot add comment once validation got failed even for 'either add or remove' message'

components/src/core/components/Table/ClassicTable.vue, components/src/core/components/Table/__tests__/__snapshots__/classic-table.spec.ts.snap
=> ENT - RMP-679 - RMP-679 - added class attribute support for cells in classic table component

components/src/core/components/List/list.scss
=> empty-msg caption color css updated

components/src/core/components/ProgressBar/brogressBar.scss
=> progressBar value changing animation added

changelog.md, components/src/core/components/Segments/Segments.vue, components/src/core/components/Segments/__tests__/__snapshots__/segments.spec.ts.snap, components/src/core/components/Segments/segments.scss
=> ENT - RR2-551 - Add Key Board Accessibility

components/src/core/components/Comments/Comment.vue
=> ENT - RMP-915 - show required validation message for empty spaces in single comment

components/src/core/components/List/List.vue
=> list-side-panel-spacer margin removed when the left panel is unavailable

components/src/core/components/Input/Select/SelectInputButton.vue
=> ENT - RR2-410 - Add click ability to whole select input button

components/src/core/components/InputField/InputField.vue, components/src/core/components/InputField/InputGroup.vue, components/src/core/components/InputField/__tests__/input-field.spec.ts, storybook/stories/core/components/InputField/InputField.stories.js
=> support custom styles for input hint

components/src/core/components/ProgressBar/_variables.scss
=> progressBar-linear-color change

components/src/core/components/Form/Form.vue, components/src/core/components/SchemaForm/SchemaForm.vue
=> RMP-938 enable adding/removing focusable element in form

components/src/core/components/Input/FileInput.vue, components/src/core/components/Input/__tests__/__snapshots__/file-input.spec.ts.snap, components/src/core/components/Input/file-input.scss, components/src/core/components/InputField/__tests__/__snapshots__/input-field.spec.ts.snap
=> ENT - RMP-917 - Corrected the styles of the readonly mode and applied the same for the disabled mode as per Mike

components/src/core/components/Input/Autocomplete/AutocompleteInput.vue, components/src/core/components/Input/Autocomplete/autocomplete-input.scss
=> ENT - RMP-921 - fixed disabled / read only background color issue

components/src/core/components/TableSidebar/TableSidebar.vue, components/src/core/components/TableSidebar/__tests__/__snapshots__/TableSidebar.spec.ts.snap, components/src/core/components/TableSidebar/table-left-panel.scss, storybook/stories/core/components/List/list-with-sidebar/left-panel.table.list.ts, storybook/stories/core/components/TableSidebar/TableSidebar.story.vue, storybook/stories/core/components/TableSidebar/TableSidebarWithIcons.story.vue, storybook/stories/core/components/TableSidebar/tableSidebar.stories.js
=> Tablesidebar3ent

components/src/core/components/Input/Autocomplete/QuickSearchInput.vue
=> LAN-49 - bug fix - removed color overriding after discussing with Mike

components/src/core/components/Input/TreeSelect/TreeSelect.vue, components/src/core/components/Input/TreeSelect/tree-select-input.scss, storybook/stories/core/components/treeSelect/TreeSelect.stories.js, storybook/stories/core/components/treeSelect/TreeSelectNarrow.story.vue
=> LAN-69 - bug fix

components/src/core/components/CardTable/CardTable.vue, components/src/core/components/CardTable/Header/DefaultCardHeader.vue, components/src/core/components/List/List.vue
=> OXD List changes

components/package.json, components/src/core/components/Button/GlassButton.vue, components/src/core/components/Button/__tests__/__snapshots__/glass-button.spec.ts.snap, package.json
=> OHRM5X-1734: OXD glass button fix disabled

components/src/core/components/CardTable/Cell/__tests__/__snapshots__/table-select-input.spec.ts.snap, components/src/core/components/Input/Select/SelectDropdown.vue, components/src/core/components/Input/Select/SelectInput.vue, components/src/core/components/Input/Select/select-input.scss, components/src/core/components/Input/__tests__/__snapshots__/select-dropdown.spec.ts.snap, components/src/core/components/Input/__tests__/select-input.spec.ts, components/src/core/components/Pagination/__tests__/__snapshots__/pagination.spec.ts.snap, storybook/stories/core/components/Input/SelectInput.stories.js
=> ENT- LAN-99 - Added spinner loader to the select dropdown component

components/src/core/components/Input/Select/SelectDropdown.vue, components/src/core/components/Input/__tests__/__snapshots__/select-dropdown.spec.ts.snap
=> ENT - LAN-75 - Added localization support for No results found in SelectDropdown component

components/src/core/components/Comments/Comment.vue, components/src/core/components/Comments/Comments.vue, components/src/core/components/Comments/comment.scss, storybook/stories/core/components/Comments/Comments.stories.js
=> ENT - LAN-108 - Added custom group label template support for comment component

components/src/core/components/Input/TreeSelect/tree-select-input.scss, storybook/stories/core/components/treeSelect/TreeSelect.story.vue
=> fixed tree select arrow alignment

components/package.json, components/src/core/components/Chart/BarChart.vue, components/src/core/components/Chart/Legend.vue, components/src/core/components/Chart/PieChart.vue, components/src/core/components/Chart/__tests__/__snapshots__/legend.spec.ts.snap, components/src/core/components/Chart/__tests__/__snapshots__/pie-chart.spec.ts.snap, components/src/core/components/Chart/__tests__/legend.spec.ts, components/src/core/components/Chart/__tests__/pie-chart.spec.ts, components/src/core/components/Chart/_variables.scss, components/src/core/components/Chart/chart.ts, components/src/core/components/Chart/legend.scss, components/src/core/components/Chart/pie-chart.scss, components/src/core/components/Chart/plugins/barfillPlugin.ts, components/src/core/components/Chart/plugins/labelPlugin.ts, components/src/core/components/Chart/plugins/tooltipPlugin.ts, components/src/core/components/Chart/types.ts, storybook/stories/core/components/Charts/BarChart.stories.js, storybook/stories/core/components/Charts/Charts.stories.js, storybook/stories/core/components/Charts/Dashboard.story.vue, storybook/stories/core/components/Charts/PieChart.stories.js, storybook/stories/core/components/Chip/Chip.stories.js, yarn.lock
=> TAR-88 Charts addition  for ent branch

changelog.md, components/src/core/components/InfoBox/InfoBox.vue, components/src/core/components/InfoBox/__tests__/__snapshots__/info-box.spec.ts.snap, components/src/core/components/InfoBox/info-box.scss, storybook/stories/core/components/InfoBox/InfoBox.stories.js
=> ENT - LAN-188 - Added clickable text to infobox component

components/src/core/components/Icon/icons.ts
=> adding LAN-165 icons

components/src/core/components/Segments/Segments.vue, components/src/core/components/Segments/__tests__/__snapshots__/segments.spec.ts.snap, components/src/core/components/Segments/__tests__/segments.spec.ts, storybook/stories/core/components/Segments/Segments.stories.js
=> ENT - LAN-179 - added icon size support to the Segments component

components/package.json, components/src/core/components/Button/GlassButton.vue, components/src/core/components/Buzz/BuzzPostInput.vue, components/src/core/components/CardTable/Cell/Actions.vue, components/src/core/components/CardTable/Table/TableHeaderCell.vue, components/src/core/components/CardTable/Table/TableHeaderSortDropdown.vue, components/src/core/components/CardTable/__tests__/__snapshots__/table-header-cell.spec.ts.snap, package.json
=> OHRM5X-1928: Fix cardtable broken issues after lint changes

components/src/core/components/Chip/Chip.vue, components/src/core/components/Input/Autocomplete/AutocompleteChips.vue, components/src/core/components/Input/Autocomplete/AutocompleteEmail.vue, components/src/core/components/Input/Autocomplete/autocomplete-input.scss, components/src/core/components/InputField/InputField.vue, components/src/core/components/InputField/types.ts, components/src/core/components/TinyMce/tinymce.scss, package.json, storybook/stories/core/components/Input/AutocompleteCustomChips.story.vue, storybook/stories/core/components/Input/AutocompleteEmailMode.story.vue, storybook/stories/core/components/Input/AutocompleteInput.stories.js, storybook/stories/core/components/SchemaForm/SchemaForm.stories.js
=> ENT - LAN-177 - Autocomplete email implementation

components/src/core/components/TinyMce/TinyMce.vue
=> ENT - LAN-177 - Added ID prop support to TinyMCE editor

components/src/core/components/TinyMce/TinyMce.vue
=> LAN-249 - added blur / focus-out event support for tinymce

changelog.md, components/src/core/components/Input/Autocomplete/AutocompleteInput.vue
=> LAN-276 - handled search term resetting issue in autcompleteinput when on keypress enter

components/package.json, components/src/composables/__tests__/useField.spec.ts, components/src/composables/__tests__/useFormValidation.spec.ts, components/src/composables/types.ts, components/src/composables/useField.ts, package.json
=> OHRM5X-1292: Form validation run async validation sequentially

components/package.json, components/src/core/components/Layout/Layout.vue, components/src/core/components/Topbar/Navigation.vue, components/src/core/components/Topbar/Topbar.vue, components/src/core/components/Topbar/navigation.scss, package.json, storybook/stories/core/components/Layout/LayoutSimple.story.vue
=> OHRM5X-797: OXD Navigation action slot added

changelog.md, components/src/core/components/TinyMce/skins/lightgray/content.module.css
=> LAN-389 reverted

components/src/core/components/TinyMce/TinyMce.vue, components/src/core/components/TinyMce/tinymce.scss
=> LAN-389 / 370

components/src/core/components/Chip/Chip.vue
Fixed the oxd chip rendering issue affected by LAN-177
=> ENT - GD-365 - bug fix

components/package.json
=> ENT - GD-365 - set @tinymce/tinymce-vue version to 5.0.0

package.json, src/components/CardTable/Table/TableHeaderSortDropdown.vue
=> OHRM5X-2202: Fix descending typo issue

components/src/core/components/Comments/Comments.vue, components/src/core/components/Comments/comments.scss, components/src/core/components/Comments/types.ts
=> LAN-571 - defined the scroll behaviour of the Comments component

components/src/core/components/Comments/Comment.vue
=> LAN-571 - enabled keypress enter save for single comments

components/src/core/components/CardTable/Cell/Checkbox.vue, components/src/core/components/CardTable/Cell/Date.vue, components/src/core/components/CardTable/Cell/Link.vue, components/src/core/components/CardTable/Cell/LinkWithPill.vue, components/src/core/components/CardTable/Cell/ProfilePicture.vue, components/src/core/components/CardTable/Cell/TableSelectInput.vue, components/src/core/components/CardTable/Cell/cell-mixin.ts, components/src/core/components/ListTable/CellContainer.vue, components/src/core/components/ListTable/Default.vue, components/src/core/components/ListTable/ListTable.vue, components/src/core/components/Skeleton/Skeleton.vue, components/src/core/components/Skeleton/__tests__/Skeleton.spec.ts, components/src/core/components/Skeleton/__tests__/__snapshots__/Skeleton.spec.ts.snap, components/src/core/components/Skeleton/_variables.scss, components/src/core/components/Skeleton/skeleton.scss, storybook/stories/core/components/ListTable/ListSkeleton.story.vue, storybook/stories/core/components/ListTable/Table.stories.js, storybook/stories/core/components/Skeleton/CustomSkeleton.story.vue, storybook/stories/core/components/Skeleton/Skeleton.stories.js
=> LAN-611: OXD-Skeleton component added

package.json, scripts/post-install.js
=> CTOO-10: Add post install script to OXD library

changelog.md, components/src/core/components/InfoBox/InfoBox.vue, storybook/stories/core/components/InfoBox/InfoBox.stories.js, storybook/stories/core/components/InfoBox/InfoBoxDetails.story.vue
=> TAR-1066: Updated the info-box component supoprting with slots

components/src/composables/types.ts, components/src/composables/useField.ts, components/src/core/components/Input/MultiSelect/MultiSelectInput.vue, components/src/core/components/InputField/InputField.vue, components/src/core/components/SchemaForm/SchemaForm.vue, components/src/core/components/SchemaForm/types.ts, storybook/stories/core/components/SchemaForm/SchemaForm.stories.js
=> LAN-455 / 489 - Set field validations dirty when initialising schema form elements

components/src/core/components/PopOverButton/PopOverButton.vue, components/src/core/components/PopOverButton/PopOverButtonDropDownOption.vue, components/src/core/components/PopOverButton/__tests__/__snapshots__/pop-over-button.spec.ts.snap, components/src/core/components/PopOverButton/__tests__/pop-over-button.spec.ts, components/src/core/components/PopOverButton/pop-over-button.scss, components/src/core/components/PopOverButton/types.ts, storybook/stories/core/components/PopOverButton/PopOverButton.stories.js, storybook/stories/core/components/PopOverButton/PopOverButtonLongTextOption.story.vue, storybook/stories/core/components/PopOverButton/PopOverButtonTemplateOption.story.vue, storybook/stories/core/components/PopOverButton/PopOverButtonTextOption.story.vue
=> TAR-884 - Added Pop Over Button Component

components/src/core/components/PopOverButton/types.ts
=> TAR-884 - Changed the type of option

components/src/core/components/PopOverButton/PopOverButton.vue
=> TAR-884 - Validator function changed to an arrow function

components/src/composables/useFlashing.ts, components/src/core/components/List2/List2.vue, components/src/core/components/List2/__tests__/List2.spec.ts, components/src/core/components/List2/__tests__/__snapshots__/List2.spec.ts.snap, components/src/core/components/List2/_variables.scss, components/src/core/components/List2/list2.scss, components/src/core/components/List2Sidepanel/StatusTabPanel.vue, components/src/core/components/List2Sidepanel/__tests__/StatusTabPanel.spec.js, components/src/core/components/List2Sidepanel/__tests__/__snapshots__/StatusTabPanel.spec.js.snap, components/src/core/components/List2Sidepanel/_variables.scss, components/src/core/components/List2Sidepanel/status-tab-panel.scss, components/src/core/components/List2Sidepanel/types.ts, components/src/core/components/List2Tabs/List2Tabs.vue, components/src/core/components/List2Tabs/__tests__/List2Tabs.spec.ts, components/src/core/components/List2Tabs/__tests__/__snapshots__/List2Tabs.spec.ts.snap, components/src/core/components/List2Tabs/_variables.scss, components/src/core/components/List2Tabs/list2-tabs.scss, components/src/core/components/List2Tabs/types.ts, components/src/core/components/List2Title/List2Title.vue, components/src/core/components/List2Title/__tests__/List2Title.spec.ts, components/src/core/components/List2Title/__tests__/__snapshots__/List2Title.spec.ts.snap, components/src/core/components/List2Title/_variables.scss, components/src/core/components/List2Title/list2-title.scss, components/src/core/components/ListTable/ListTable.vue, storybook/stories/core/components/List2/Default.story.vue, storybook/stories/core/components/List2/List2.stories.js, storybook/stories/core/components/List2/ListTopTabs.story.vue, storybook/stories/core/components/List2/ListTopTitle.story.vue, storybook/stories/core/components/List2/NoSidepanel.story.vue, storybook/stories/core/components/ListTable/ListTable.story.vue
=> LAN-613: List v2 components added

changelog.md, components/src/core/components/InfoBox/InfoBox.vue
=> Tar 1193: Observed Keyboard Accessibility issues

components/src/core/components/Comments/Comments.vue
=> LAN-766 - validated and checked 'commentGroupsList' exists before trigger scroll

components/src/core/components/Input/Number/Number.vue
=> LAN-715 - changed onChange event to onKeyup

components/src/core/components/Input/Number/Number.vue
=> LAN-715 - set default value when the value is required and exceeded the min max values

components/src/core/components/Input/Number/Number.vue, components/src/core/components/Input/Number/number.scss, components/src/core/components/Input/__tests__/number.spec.ts, storybook/stories/core/components/Input/Number.stories.js, storybook/stories/core/components/SchemaForm/SchemaForm.stories.js
=> LAN - goal weights number component issue fix

components/src/core/components/Input/Number/Number.vue, storybook/stories/core/components/Input/Number.stories.js, storybook/stories/core/components/Input/NumberEvents.story.vue
=> Number Input -  issue corrected

components/src/core/components/Button/_variables.scss, components/src/core/components/Icon/_variables.scss
=> TEC-308: OXD Icon button disabled color changed

changelog.md, components/src/core/components/Icon/icons.ts
=> HT-370 - Add oxd-chevron-up-border-less and oxd-chevron-down-border-less Icons

changelog.md, components/src/core/components/Input/Select/SelectInputButton.vue, components/src/core/components/Input/__tests__/select-input.spec.ts, storybook/stories/core/components/Input/SelectInputButton.stories.js
=> HT-370 - Introduce a prop to change dropdown trigger open-close icons.

changelog.md, components/src/core/components/Icon/icons.ts
=> HT-370 Add oxd-lock-slash

changelog.md, components/src/core/components/Input/FileInput.vue, components/src/core/components/ListTable/CellContainer.vue, components/src/core/components/ListTable/ClickableCell.vue, components/src/core/components/ListTable/ListTable.vue, components/src/core/components/ListTable/Truncate.vue, components/src/core/components/ListTable/__tests__/__snapshots__/list-table.spec.ts.snap, components/src/core/components/ListTable/list-table.scss, components/src/core/components/SchemaForm/SchemaForm.vue
=> TEC-386: Truncate cell type added

changelog.md, components/src/directives/focus-first-element/index.ts
=> TEC-431: Focus first directive prevent scroll on focus

changelog.md, components/src/core/components/ListTable/list-table.scss
=> TEC-467: Shrink OXD list table headers when there are no space

changelog.md, components/src/core/components/Input/FileInput.vue
This pull request fixes the issue where empty files (files with 0 bytes) selected from the file input, but the output files were not being created.
=> GD-899: OXD File input allow uploading files without content

changelog.md, components/src/core/components/Icon/icons.ts, components/src/core/components/Input/Select/SelectInputButton.vue
=> LAN-1006: Adding shortlist icon to OXD Icons

changelog.md, components/src/core/components/Button/_variables.scss, components/src/core/components/Button/button.scss, components/src/core/components/Button/types.ts, components/src/styles/_colors.scss, storybook/stories/core/components/Button/Button.stories.js
=> LAN-1006: Add label-feedback-reject button type to OXD button

changelog.md, components/src/core/components/CardTable/Decorator/DefaultCardMobile.vue, components/src/core/components/CardTable/Decorator/DefaultCardWeb.vue, components/src/core/components/CardTable/Decorator/card.scss, components/src/core/components/CardTable/__tests__/__snapshots__/card-table.spec.ts.snap, components/src/core/components/ListTable/CellContainer.vue, components/src/core/components/ListTable/ListTable.vue, components/src/core/components/ListTable/TableHeader.vue, components/src/core/components/ListTable/TableHeaderCell.vue, components/src/core/components/ListTable/__tests__/__snapshots__/list-table.spec.ts.snap, components/src/core/components/ListTable/__tests__/list-table.spec.ts, components/src/core/components/ListTable/_variables.scss, components/src/core/components/ListTable/table-header-cell.scss, components/src/core/components/ListTable/table-header.scss
=> TEC-609: Fix skeleton loader related issues in OXD list table
